Custom generators for plain ruby classes
redpanthers/starter pull request #19
Opened 2018-03-18 12:13 UTC by redtachyons

1. Service object
2. Form object
3. Query object

2018-03-21 10:34 UTC, coderhs requested changes

2018-03-21 10:34 UTC, coderhs commented on lib/generators/form_object/USAGE
> +        app/services/thing.rb
If its a form object then we need it in `app/forms`

2018-03-21 10:34 UTC, coderhs commented on lib/generators/rspec/form_object/form_object_generator.rb
> +class FormObjectGenerator < Rails::Generators::NamedBase
Intending.

2018-03-21 10:34 UTC, coderhs commented on lib/generators/service_object/templates/service_object.rb.tt
> +class <%= class_name %>
In the main template and project, in general, I would like to keep format `ClassNameService`, didn't want to break the convention in clickx but here would like to keep the postfix service.

2018-06-03 04:44 UTC, coderhs approved these changes

2018-06-03 04:45 UTC, coderhs commented
@tachyons I have made changes to your `Custom Generator`. Basically, I changed the nomenclature used. Do share your review.

2018-06-03 06:02 UTC, redtachyons commented
LGTM

2018-06-03 10:10 UTC, merged